USE CLASSICMODELS;

SELECT 
    CUSTOMERS.CUSTOMERNUMBER,
    CUSTOMERNAME,
    PHONE,
    PAYMENTDATE,
    AMOUNT
FROM
    CUSTOMERS
        INNER JOIN
    PAYMENTS ON CUSTOMERS.CUSTOMERNUMBER = PAYMENTS.CUSTOMERNUMBER
WHERE
    CITY = 'LAS VEGAS';

SELECT 
    CUSTOMERS.CUSTOMERNUMBER,
    CUSTOMERS.CUSTOMERNAME,
    ORDERS.ORDERNUMBER,
    ORDERS.STATUS
FROM
    CUSTOMERS
        LEFT JOIN
    ORDERS ON CUSTOMERS.CUSTOMERNUMBER = ORDERS.CUSTOMERNUMBER
