USE CLASSICMODELS;

SELECT 
    `STATUS`
FROM
    ORDERS
GROUP BY `STATUS`;

SELECT 
    `STATUS`, COUNT(*) AS NO_OF_STATUS
FROM
    ORDERS
GROUP BY `STATUS`;

SELECT 
    `STATUS`, SUM(QUANTITYORDERED * PRICEEACH) AS AMOUNT
FROM
    ORDERS
        INNER JOIN
    ORDERDETAILS ON ORDERS.ORDERNUMBER = ORDERDETAILS.ORDERNUMBER
GROUP BY STATUS;

SELECT 
    ORDERNUMBER, SUM(QUANTITYORDERED * PRICEEACH) AS TOTAL
FROM
    ORDERDETAILS
GROUP BY ORDERNUMBER;